use_frameworks!

platform :ios, '9.0'

target 'UIScrollView-InfiniteScrollSwift_Example' do
  pod 'UIScrollView-InfiniteScrollSwift', :path => '../'

  target 'UIScrollView-InfiniteScrollSwift_Tests' do
    inherit! :search_paths

    
  end
end
